# Generated by Django 6.0.4 on 2026-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-creat_at'], name='Store_produ_creat_a_b4e6eb_idx'),
        ),
    ]
