# Generated by Django 6.0.4 on 2026-04-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_product_store_produ_id_ab32c8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='Store_produ_id_b9d62a_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='Store_produ_id_ab32c8_idx'),
        ),
    ]
