# Generated by Django 6.0.4 on 2026-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_product_store_produ_id_b9d62a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae neque perferendis excepturi', max_length=1500),
        ),
    ]
