# Generated by Django 6.0.4 on 2026-04-28 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.categry'),
        ),
    ]
