# Generated by Django 6.0.4 on 2026-04-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_product_categry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categry',
            new_name='category',
        ),
    ]
