# Generated by Django 6.0.4 on 2026-04-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_categry_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categry',
            new_name='Category',
        ),
    ]
