# Generated by Django 6.0.4 on 2026-04-20 14:11

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='acount',
            managers=[
                ('create_acount', django.db.models.manager.Manager()),
            ],
        ),
    ]
