# Generated by Django 6.0.4 on 2026-04-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_alter_acount_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='acount',
            managers=[
            ],
        ),
    ]
