# Generated by Django 6.0.4 on 2026-04-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_alter_acount_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acount',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
