# Generated by Django 6.0.4 on 2026-04-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0004_alter_acount_is_active_alter_acount_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
