# Generated by Django 6.0.4 on 2026-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0005_alter_acount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
