# Generated by Django 6.0.4 on 2026-05-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpay',
            old_name='Pay_phone',
            new_name='pay_phone',
        ),
    ]
