# Generated by Django 6.0.4 on 2026-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_pay_phone_orderpay_pay_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpay',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
